### ISSUE TITLE
Changing the x axis of curves causes an error

### ISSUE THREAD

**Issue by FastAndFishious** [DBooots/KerbalWindTunnel#13]
Wouldn't be surprised if this is an issue on my side, but I am facing the following bug.

Here, everything is behaving as expected.
![Capture d’écran (72)](https://user-images.githubusercontent.com/99523534/153697312-b9ddf817-f870-4225-a26c-ec9719b3764b.png)

The x axis is changed, still working normally.
![Capture d’écran (73)](https://user-images.githubusercontent.com/99523534/153697400-cd576423-b368-4b40-9cf9-0e70207fdb34.png)

However, from here changing anything, such as pressing "Update Vessel", breaks everything.
![Capture d’écran (74)](https://user-images.githubusercontent.com/99523534/153697601-300732a5-26f5-4501-8508-adbe7c23cf8c.png)

The console is also spammed with "Exception: ObjectDisposedException: The CancellationTokenSource has been disposed."
![Capture d’écran (75)](https://user-images.githubusercontent.com/99523534/153697789-ec512a53-b54d-4c7a-9459-b1dbf85228a4.png)

From here, the only solution I found is to exit and reenter the SPH.
Thank you for taking the time to read my bug report, and for creating this mod!

**Comment by DBooots** [comment]
There was an issue with a lamda expression inadvertently disposing an active CancellationToken. The fix has been committed and will be included in 1.3.1.1.
