### ISSUE TITLE
CSV export not actually exporting anything

### ISSUE THREAD

**Issue by Aivech** [DBooots/KerbalWindTunnel#6]
Game version 1.7.1
Mod version 1.2.3 via CKAN
On clicking the save button no file is saved in /WindTunnel/PluginData/

**Comment by DBooots** [comment]
Fix is made in https://github.com/DBooots/Unity-Graphing/commit/55b89e86cff0200930f1f15f205f311927e27089

The new update to the graphing library will be included in the next release.
